# Generated by Django 2.2.3 on 2019-08-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abc',
            fields=[
                ('bun', models.IntegerField(primary_key=True, serialize=False)),
                ('irum', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'abc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('bwrite', models.DateTimeField(blank=True, null=True)),
                ('readcnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buser',
            fields=[
                ('buser_no', models.IntegerField(primary_key=True, serialize=False)),
                ('buser_name', models.CharField(max_length=10)),
                ('buser_loc', models.CharField(blank=True, max_length=10, null=True)),
                ('buser_tel', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'buser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gogek',
            fields=[
                ('gogek_no', models.IntegerField(primary_key=True, serialize=False)),
                ('gogek_name', models.CharField(max_length=10)),
                ('gogek_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('gogek_jumin', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'db_table': 'gogek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jikwon',
            fields=[
                ('jikwon_no', models.IntegerField(primary_key=True, serialize=False)),
                ('jikwon_name', models.CharField(max_length=10)),
                ('buser_num', models.IntegerField()),
                ('jikwon_jik', models.CharField(blank=True, max_length=10, null=True)),
                ('jikwon_pay', models.IntegerField(blank=True, null=True)),
                ('jikwon_ibsail', models.DateField(blank=True, null=True)),
                ('jikwon_gen', models.CharField(blank=True, max_length=4, null=True)),
                ('jikwon_rating', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'jikwon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappBoardtab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('cont', models.TextField()),
                ('bip', models.CharField(max_length=39)),
                ('bdate', models.DateTimeField()),
                ('readcnt', models.IntegerField()),
                ('gnum', models.IntegerField()),
                ('onum', models.IntegerField()),
                ('nested', models.IntegerField()),
            ],
            options={
                'db_table': 'myapp_boardtab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pymem',
            fields=[
                ('bun', models.IntegerField(primary_key=True, serialize=False)),
                ('irum', models.CharField(max_length=12)),
                ('junwha', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'pymem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sangdata',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('sang', models.CharField(blank=True, max_length=20, null=True)),
                ('su', models.IntegerField(blank=True, null=True)),
                ('dan', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sangdata',
                'managed': False,
            },
        ),
    ]
